### ISSUE TITLE
Datepicker problem

### ISSUE THREAD

**Issue by loter** [wbraganca/yii2-dynamicform#10]
Hi!

You suggested me to switch from yii datepicker to kartik datepicker, and for some reason the datepicker for cloned form fields is not working. 

I'm definetely using latest versions of everything, I just re-run the composer update.. 

```

<?php
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\URL;

use frontend\models\TitlesList;
use frontend\models\Yesorno;
use frontend\models\Countries;
use frontend\models\EmployeeEmployment;

use kartik\widgets\ActiveForm;
use kartik\widgets\DatePicker;
use kartik\widgets\Select2;
use wbraganca\dynamicform\DynamicFormWidget;
?>
<?php
$form = ActiveForm::begin(['id'=>'registration-step-1','options'=>['class'=>'form-block']]);
?>
<?php
$titleslist = ArrayHelper::map(TitlesList::find()->orderBy('title_order')->all(), 'title_id', 'title_name');
$yesornolist = ArrayHelper::map(Yesorno::find()->orderBy('yesorno_order')->all(), 'yesorno_id', 'yesorno_name');
$countrylist = ArrayHelper::map(Countries::find()->orderBy('country_id')->all(), 'country_id', 'country_name');
?>
<?= Html::activeDropDownList($modelEmployee, 'employee_title', $titleslist, array('class'=>'form-control','prompt'=>'Please Select Title')) ?>
<?= $form -> field ($modelEmployee,'employee_firstname')  ?>  
<?= $form -> field ($modelEmployee,'employee_lastname') ?>
<?= $form -> field ($modelEmployee,'employee_workpermit')->radiolist($yesornolist,['itemOptions' => ['class' =>'radio-inline']]) ?>

<p>Contact Information</p>
<?= $form -> field ($modelEmployee,'employee_email') ?>
<?= $form -> field ($modelEmployee,'employee_phone') ?>
<?= $form -> field ($modelEmployee,'employee_mobile') ?>
<?= $form -> field ($modelEmployee,'employee_address') ?>
<?= $form -> field ($modelEmployee,'employee_town') ?>
<?= $form -> field ($modelEmployee,'employee_country') ?>
<?= $form -> field ($modelEmployee,'employee_postcode') ?>
<p>Education</p>
<?  
//echo $form -> field ($modelEmployee,'employeeQualifications') 
?>
<?php DynamicFormWidget::begin([
                'dynamicItems' => '#form-qualifications',
                'dynamicItem' => '.form-qualifications-item',
                'model' => $modelsQualifications[0],
                'formId' => 'registration-step-1',
                'formFields' => [
                    'employee_employment_position',
                    'employee_employment_start_date',
                    'employee_employment_end_date',
                    'employee_employment_reason',
                    'employee_employment_organisation',
                    'employee_employment_town',
                    'employee_employment_country',
                ],
                'options' => [
                    'limit' => 5,
                ]
            ]); ?>
<div id="form-qualifications">
            <?php foreach ($modelsQualifications as $i => $modelQualifications): ?>
                <div class="form-qualifications-item panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title pull-left">Qualifications</h3>
                        <div class="pull-right">
                            <button type="button" class="clone btn btn-success btn-xs"><i class="glyphicon glyphicon-plus"></i></button>
                            <button type="button" class="delete btn btn-danger btn-xs"><i class="glyphicon glyphicon-minus"></i></button>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-body">
                        <?php
                            // necessary for update action.
                            if (!$modelQualifications->isNewRecord) {
                                echo Html::activeHiddenInput($modelQualifications, "[{$i}]id");
                            }
                        ?>
                        <?= $form->field($modelQualifications, "[{$i}]employee_employment_position")->textInput(['maxlength' => 64]) ?>
                        <div class="row">
                            <div class="col-sm-6">
                                <?php
                                    echo $form->field($modelQualifications, "[{$i}]employee_employment_start_date")->widget(DatePicker::classname(), [
                                    'options' => ['placeholder' => 'Please enter employment start date'],
                                    'pluginOptions' => [
                                    'autoclose'=>true,
                                    'format' => 'dd/mm/yyyy'
                                    ]
                                    ]);

                                ?>
                            </div>
                            <div class="col-sm-6">
                                <?php
                                    echo $form->field($modelQualifications, "[{$i}]employee_employment_end_date")->widget(DatePicker::classname(), [
                                    'options' => ['placeholder' => 'Please enter employment end date'],
                                    'pluginOptions' => [
                                    'autoclose'=>true,
                                    'format' => 'dd/mm/yyyy'
                                    ]
                                    ]);

                                ?>
                            </div>
                        </div><!-- .row -->
                        <div class="row">
                            <div class="col-sm-4">
                                <?= $form->field($modelQualifications, "[{$i}]employee_employment_reason")->textInput(['maxlength' => 64]) ?>
                            </div>
                            <div class="col-sm-4">
                                <?= $form->field($modelQualifications, "[{$i}]employee_employment_organisation")->textInput(['maxlength' => 32]) ?>
                            </div>
                            <div class="col-sm-4">
                                <?= $form->field($modelQualifications, "[{$i}]employee_employment_town")->textInput(['maxlength' => 15]) ?>
                            </div>
                            <div class="col-sm-4">

                            </div>
                        </div><!-- .row -->
                    </div>
                </div>
            <?php endforeach; ?>
            </div>          
<?php DynamicFormWidget::end(); ?>
<p>Employment in the last two years</p>

<p>Languages</p>

<p>Additional information</p>
<div class="form-group">
        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary']) ?>
    </div>
<?php
ActiveForm::end();
?>


```

Please advice
Thanks, D.

**Comment by synatree** [comment]
It's hard to solve the problem you are having.  I don't think this extension will currently support what you are trying to do, because the JavaScripts of later cloned widgets conflicts with earlier ones.  I would suggest you check out yii2-dynamic-relations instead.

**Comment by jgrasta** [comment]
<?php
$form = ActiveForm::begin(['id'=>'registration-step-1','options'=>['class'=>'form-block']]);
?>
is it possible to have 'registration-step-2' in the same form

**Comment by cyanoboy** [comment]
Guys have you found a solution to this problem? There is any datepicker plugin that works with yii2-dynamicform?

**Comment by Pla2aroi** [comment]
this works for me

- to path vendor\wbraganca\yii2-dynamicform\assets\yii2-dynamic-form.js

//EDIT
// "kartik-v/yii2-widget-datepicker"
var $hasDatepicker = $(widgetOptionsRoot.widgetItem).find('[data-krajee-kvdatepicker]');
        if ($hasDatepicker.length > 0) {
            $hasDatepicker.each(function() {
                $(this).parent().removeData().kvDatepicker('remove');
                $(this).parent().kvDatepicker(eval($(this).attr('data-krajee-kvdatepicker')));
            });
        }

//ปลาทู อร่อย

**Comment by javaharut** [comment]
Yes the above mentioned is worked, I think this is because yii2-dynamicform uses old datepicker class

**Comment by filipajdacic** [comment]
Hi, 
I have DynamicForm using default jQuery UI datepicker and I have solved this problem on the following way:

**In my view/form:**
```php
<?= $form->field($experience, "[{$i}]date_from")->widget(\yii\jui\DatePicker::classname(), [
					    					//'language' => 'ru',
					    					'dateFormat' => "dd-M-yyyy",
					    					'options' => ['class' => 'form-control picker']
]) ?>
```

**In /vendors/wbraganca/yii2-dynamicform/assets/yii2-dynamicform.js:**

```javascript
    var _restoreSpecialJs = function(widgetOptions) {
        var widgetOptionsRoot = _getWidgetOptionsRoot(widgetOptions);

        $( ".picker" ).each(function() {
            $( this ).datepicker();
        });
```

Now, datepicker works like a charm!

**Comment by Shanthijagan** [comment]
The solution by filipajdacic  said is not working.

**Comment by filipajdacic** [comment]
It's not working because I am using native jquery datepicker and you are
probably using kartik-v datepicker.

Try adding this code:

$(".dynamicform_wrapper").on('afterInsert', function(e, item) {
    var datePickers = $(this).find('[data-krajee-kvdatepicker]');
    datePickers.each(function(index, el) {
        $(this).parent().removeData().kvDatepicker('remove');
        $(this).parent().kvDatepicker(eval($(this).attr('data-krajee-kvdatepicker')));
    });
});




--
*Filip Ajdačić*
<?= 'Web developer' ?>
*skype:* filipajdacic
*linkedin:* Filip Ajdacic
*phone: *(+381) 61 2092 081

2016-04-19 11:22 GMT+02:00 Shanthijagan <notifications@github.com>:

**Comment by InsaneSkull** [comment]
Well, It's an temporary solution. [Have a look.](http://stackoverflow.com/questions/40651844/wbraganca-yii2-dynamic-form-date-picker-issue/40734508#40734508)

**Comment by pczi** [comment]
The code above works for me, it initializes the popup to select a date on dynamically created controls.

What does not work is to copy the DISPLAYED control value to the HIDDEN control value, which will be sent to the server via POST.

My solution was to catch the submit button and manually transfer and convert from DISP to HIDDEN control.

However, I am not able to access the datepicker.parsedate function, so converting from displaySettings to saveSettings is "hardcoded", here my code to translate from 'dd/MM/yyyy' to php:Y-m-d'

// javascript to handle kvDatepicker created dynamically
// just before submitting, we read the DISPLAYED form control
// reformat from dd/MM/yyyy to phpY-m-d and update the value
// of the HIDDEN form control (which is sent as POST variable)

$script = <<< JS
$('#form-registerplus').on('submit', function(e){
    $( ".krajee-datepicker" ).each(function() {
        var dparts = $(this).val().split("/");
        var disp = $(this).attr('id');
        var dispd = new Date(dparts[2], dparts[1]-1, dparts[0]);
        var hidd = "#"+disp.replace('-disp','');
        var hiddd = dparts[2]+'-'+dparts[1]+'-'+dparts[0];
        if ($(hidd).val() != hiddd) {
            $(hidd).val(hiddd);
        }
   });
});

**Comment by aludayanan** [comment]
This works for me

// "kartik-v/yii2-widget-datepicker"
        var $hasDatepicker = $(widgetOptionsRoot.widgetItem).find('[data-krajee-kvdatepicker]');
        if ($hasDatepicker.length > 0) {
            $hasDatepicker.each(function() {
                $(this).parent().removeData().kvDatepicker('initDPRemove');
                $(this).parent().kvDatepicker(eval($(this).attr('data-krajee-kvdatepicker')));
            });
        }

**Comment by den11100** [comment]
`$(".dynamicform_wrapper").on('afterInsert', function(e, item) {
        var datePickers = $(this).find('[data-krajee-kvdatepicker]');
        datePickers.each(function(index, el) {
            $(this).parent().removeData().kvDatepicker('initDPRemove');
            $(this).parent().kvDatepicker(eval($(this).attr('data-krajee-kvdatepicker')));
        });
    });`

**Comment by den11100** [comment]
put this code in your view file

```
$(".dynamicform_wrapper").on('afterInsert', function(e, item) {
        var datePickers = $(this).find('[data-krajee-kvdatepicker]');
        datePickers.each(function(index, el) {
            $(this).parent().removeData().kvDatepicker('initDPRemove');
            $(this).parent().kvDatepicker(eval($(this).attr('data-krajee-kvdatepicker')));
        });
});
```

**Comment by matiasgithub** [comment]
Esto funcionó para mi, con la configuracion  del formato de fecha
    $(".dynamicform_wrapper").on('afterInsert', function(e, item) {
        var datePickers = $(this).find('[data-krajee-kvdatepicker]');
        datePickers.each(function(index, el) {
            $(this).parent().kvDatepicker.defaults.format = "dd-mm-yyyy";
            $(this).parent().removeData().kvDatepicker('initDPRemove');
            $(this).parent().kvDatepicker(eval($(this).attr('data-krajee-kvdatepicker')));           
        });
    });
