### ISSUE TITLE
Can't create a hidden field with value

### ISSUE THREAD

**Issue by kaarleenzz** [wbraganca/yii2-dynamicform#11]
It is impossible to add a hidden field for each cloned element. 

It only works for the initial element, for all others the value is removed. I even tried to write it in plain html, even then it would remove the value. This is really weird.

**Comment by kaarleenzz** [comment]
I'm guessing this is not possible then?

**Comment by wbraganca** [comment]
You can use the event "afterClone" and set any value for your hidden field.

First define an id for DynamicFormWidget:

```php
<?php DynamicFormWidget::begin([
    'id' => 'dynamic-form-widget',
    ...
]); ?>
```

Then add the code below into your "view":

```php
<?php
$js = '
$("#dynamic-form-widget").on("afterClone", function(ev, result) {
    // your code here
});
';
$this->registerJs($js);
?>
```

**Comment by kaarleenzz** [comment]
Thank you, that seems to be working. :)

Any idea about nested dynamic forms?

**Comment by bsyyu** [comment]
I am follow your steps above for using "afterClone" event, but it doesn't work. Besides, I am using \kartik\file\FileInput, for update action, by adding new item, the image for 1st item simply duplicate in the new item. How to avoid this, as you have been done at your demo 2. Thanks for your help in advance
![capture_code](https://cloud.githubusercontent.com/assets/6166766/9331615/07498406-45f3-11e5-98e4-107133225192.JPG)
