### ISSUE TITLE
Doesn't work with kartik typeahead widget

### ISSUE THREAD

**Issue by ToRvaLDz** [wbraganca/yii2-dynamicform#12]
Any change to make it work with kartik typeahead?

https://github.com/kartik-v/yii2-widget-typeahead

Thank you

**Comment by vaibhavk01** [comment]
is the dynamic form working for typehead?

**Comment by jcabanillas** [comment]
Hi, can you change your extension to work with kartik typeahead?
https://github.com/kartik-v/yii2-widget-typeahead
Thank you in advance.

**Comment by Divan4ik** [comment]
I'll wait here too

**Comment by darkphase01** [comment]
Hi, wbraganca much thanks for such a great extension but we would love to see it work with kartik typeahead.

**Comment by sokollondon** [comment]
I tried to do. It is impossible to get the config, which is passed by 3 parameters in kvInitTA(). It is also necessary to change kartik-v/yii2-widget-typeahead so that the config is saved in a separate global js variable.
