### ISSUE TITLE
[Help] Auto Fillup Prices after choosing a Product -Select2

### ISSUE THREAD

**Issue by leonardojulius** [wbraganca/yii2-dynamicform#127]
Actually Its not an issue about the plugin
I dont know how to Auto fillup the Product Prices textInput using dynamic form..

E.g. when im Choosing a Product it auto fill the price which is Read-only, But the problem is when adding new element.. I cant find specific ID or Class on the Select2 option Class or ID

`the given ID is "select2-customerpurchaseitems-0-product_name-container" but doesnt work in js 

 <div class="col-sm-6">
                                        <?=
                                         $form->field($modelCustomerpurchase, "[{$i}]product_name")->widget(Select2::classname(), [

                                            'data'=> ArrayHelper::map(Products::find()->all(),'product_ID','product_name'),
                                             'options' => [
                                                 'placeholder' => 'Select product ...',
                                                 'class'=>'PricesZone',
                                             ],

                                             'pluginOptions' => [
                                                'allowClear' => true,
                                            ],
                                        ]);
                                        ?>
                                    </div>`

JS

`
<?php
$script = <<< JS
$('.PricesZone').change(function(){

var PricesId = $(this).val();

$.get('index.php?r=juliuscrmp/products/get-prices',{ PricesId : PricesId},function(data){
var data = $.parseJSON(data)
alert(data.product_price);

$("#customerpurchaseitems-0-product_price").attr('value',data.product_price);
});

});
JS;
$this->registerJs($script);

?>

<?php
/*`

![untitled](https://cloud.githubusercontent.com/assets/16941074/13029591/6af99066-d245-11e5-9873-7fe4cef2513d.png)

**Comment by leonardojulius** [comment]
I solve it

**Comment by kidzen** [comment]
how you solve it?mind to share?i have the same problem

**Comment by leonardojulius** [comment]
Sorry for very delay reply.. what I did is I change the ID  into-> class $('.PricesZone').change(function()  to  $("#PricesZone").change(function() and the change the attr to prop e.g.    
$("#customerpurchaseitems-1-product_price").prop('value', '')

**Comment by kidzen** [comment]
> # is for id, and (.)dot is for class...your previous code is calling the class...your new code is calling the id..


if you are indeed calling the id, then thats mean it not applicable for the next element created unless the js itterate the ID..

**Comment by kidzen** [comment]
is for id, and (.)dot is for class...your previous code is calling the class...your new code is calling the id..

if you are indeed calling the id, then thats mean it not applicable for the next element created unless the js itterate the ID..
