### ISSUE TITLE
Multiple nested widgets

### ISSUE THREAD

**Issue by kaarleenzz** [wbraganca/yii2-dynamicform#15]
Is it possible to create a DynamicFormWidget within a DynamicFormWidget ? I can add the widget within the widget but add and distract buttons all work the same - they remove the outer widgets instances.

This is what I want(example):
1 Parent can have many kids
    Many Kids, can have many toys.

I would like to be able to dynamically add kids and then dynamically add toys to each kid. Is this kind of structure/functionality possible with this widget?

**Comment by wbraganca** [comment]
@kaarleenzz Current version does not work. I'm working on a new release to support this.

**Comment by kaarleenzz** [comment]
@wbraganca that's great as it is exactly what I'm looking for. Any idea of when it could be available (couple of weeks/months/year? ) :)

**Comment by elastic-od** [comment]
Same problem. When it could be done if the project alive?

**Comment by wbraganca** [comment]
I apologize, I have not had time to work on it yet. Next week, I go back to work on the project.

**Comment by elastic-od** [comment]
Great! It is real useful plugin and it need to be developed.

**Comment by wbraganca** [comment]
Great progress at now! :D

![dynamicform-nested](https://cloud.githubusercontent.com/assets/1946359/6269014/d375584c-b837-11e4-97e9-f90c6e60d7a8.jpg)

**Comment by kaarleenzz** [comment]
Good stuff, good stuff!!! Looking forward to this :)

**Comment by elastic-od** [comment]
Looks great! )

**Comment by wbraganca** [comment]
Added support for multiple nested widgets. See new version 2.0.0

**Comment by kaarleenzz** [comment]
Will you write up an example/tutorial of this scenario?

**Comment by iijak** [comment]
Will you write up an example/tutorial for this scenario Please?
