### ISSUE TITLE
[Question]how to add 5 row details as  default for the first time page load

### ISSUE THREAD

**Issue by jordan095** [wbraganca/yii2-dynamicform#161]
Hi,
I want to ask how to add 5 row details as  default for the first time page load?
Thank you

**Comment by hscstudio** [comment]
Simple You only add this code in view form
`
if($model->isNewRecord){
$this->registerJs('
for(var i=0;i<5;i++){
	$( ".add-tools" ).click();
}
');
}
`

**Comment by jhon100** [comment]
Empty or filled with models data?

**Comment by raymonmon** [comment]
Hi, I'm having error with loading 5 row details on first time load. Where should I put the Javascript? I got this error if I put the registerJs after the widget

TypeError: $toclone.clone is not a function

Please help. Thank you!
