### ISSUE TITLE
Call to undefined method yii\base\Model::createMultiple()

### ISSUE THREAD

**Issue by ranvk** [wbraganca/yii2-dynamicform#162]
i want to ask where the static function about Model::createMultiple()  ???

**Comment by wildflower** [comment]
Did you include/reference the Model.php from the bottom of the home page? https://github.com/wbraganca/yii2-dynamicform

you need to put it in it's own namespace

**Comment by ranvk** [comment]
not matter the namespace  my yii2 yii\base\Model  have not the static function about 'createMultiple()'

**Comment by wildflower** [comment]
Because you need to copy the Model.php from the home page of this project and put it into your models directory, i.e app/models or backend/models
and then put 
use backend/models/Model;
in your Controller

**Comment by ranvk** [comment]
thx I got it

**Comment by dezhavuu** [comment]
i dont find include/reference dont to find Model.php, i have been searching for "createMultiple" and nothing.. could you please help me?

**Comment by dezhavuu** [comment]
i found it https://github.com/wbraganca/yii2-dynamicform/issues/39
