### ISSUE TITLE
Is this extenstion working nw ??

### ISSUE THREAD

**Issue by dina-samy** [wbraganca/yii2-dynamicform#18]
I'm getting this error

Argument 1 passed to DOMDocument::importNode() must be an instance of DOMNode, null given, called in C:\xampp\htdocs\iso2\vendor\yiisoft\yii2\base\Widget.php on line 73 and defined

Any help,thanks alot

**Comment by xemware** [comment]
Invalid selector specified for dynamicItems or dynamicItem property

**Comment by jackhad** [comment]
I got this error 

> Unknown Property – yii\base\UnknownPropertyException
Getting unknown property: app\models\PlanDetail::0

while implementing this 

` <?php 
               use wbraganca\dynamicform\DynamicFormWidget;
                DynamicFormWidget::begin([
                'widgetContainer' => 'dynamicform_wrapper', // required: only alphanumeric characters plus "_" [A-Za-z0-9_]
                'widgetBody' => '.container-items', // required: css class selector
                'widgetItem' => '.item', // required: css class
                'limit' => 4, // the maximum times, an element can be cloned (default 999)
                'min' => 1, // 0 or 1 (default 1)
                'insertButton' => '.add-item', // css class
                'deleteButton' => '.remove-item', // css class
                'model' => $planDetailModels,
                'formId' => 'dynamic-form',
                'formFields' => [
                    'name',
                    'value',
                    'type'

                ],
            ]); ?>`

**Comment by koloda** [comment]
$planDetailModels mus be not empty and must contain at least one empty model

Before call DynamicGrid you should do someting like this: 
```
if (empty($planDetailModels)) {
    $planDetailModels = [new YourDetailModelClass()];
}
```
