### ISSUE TITLE
Validation Max from other model

### ISSUE THREAD

**Issue by sciefylab** [wbraganca/yii2-dynamicform#186]
Dear Mate,

I have problem validation not correct when value max from other model,

Model :
``
   public function rules()
    {
        return [
            [['item_id', 'qty', 'uom_id', 'to_dept', 'user_site'], 'required'],
            [['material_req_id', 'item_id', 'uom_id', 'to_dept', 'user_site','loc_id'], 'integer'],
            [['qty'], 'number','max'=> WitemsStock::find()->where(['item_id'=>$this->item_id,'location_id'=>$this->loc_id])->select('qty')->scalar()],
            [['material_req_id'], 'exist', 'skipOnError' => true, 'targetClass' => WmaterialRequest::className(), 'targetAttribute' => ['material_req_id' => 'id']],
        ];
    }
``

![false_qty](https://cloud.githubusercontent.com/assets/16133106/21793940/d1c3ceec-d730-11e6-9147-da6f34be10ff.jpg)

please help,

thanks
sciefylab

**Comment by sciefylab** [comment]
SOLVED

MODEL:

> public function rules()
    {
        return [
            [['item_id', 'qty', 'uom_id', 'to_dept', 'user_site','loc_id'], 'required'],
            [['material_req_id', 'item_id', 'uom_id', 'to_dept', 'user_site','loc_id'], 'integer'],
            [['qty'], 'number'], 
            ['qty', 'notAllowedStock', 'params' => ['item_id' => 'item_id','loc_id'=>'loc_id']],
            [['material_req_id'], 'exist', 'skipOnError' => true, 'targetClass' => WmaterialRequest::className(), 'targetAttribute' => ['material_req_id' => 'id']],
        ];
    },

>  public function notAllowedStock($attribute,$params)
    {
        $stock = WitemsStock::find()->where(['item_id'=>$this->{$params['item_id']},'location_id'=>$this->      {$params['loc_id']}])->one()->qty;
        if($this->$attribute > $stock){
            $this->addError($attribute, 'Qty must be less than or equal to '.$stock);
        }       
    }

![meterial request](https://cloud.githubusercontent.com/assets/16133106/23115276/cce0eb6c-f77e-11e6-82e4-721989d5ef51.png)

**Comment by tonchito** [comment]
Estimate sciefylab, you have a suggestion of how to validate the detail so that there are no rows with the same data?

**Comment by sciefylab** [comment]
>  $('#dynamic-form').on('afterValidate', function (e) {

            var valx = document.querySelectorAll('select[id$=item_id]');
            var arritem = Array.from(valx);
            var result = arritem.map(function(a) {return a.value;});
            Array.from(valx).forEach(function(el){ 
                  
                  var itemid = el.id;
                  var itemval = el.value;
                  //alert(itemid);
                    var count = 0;
                    for(var i = 0; i < result.length; ++i){
                        if(result[i] == itemval)
                            count++;
                    }
                    

                    if (count > 1){
                         $('#dynamic-form').yiiActiveForm('updateAttribute', itemid, ['I have an error...']);                       
                    }

            });

        return true;
        
      }); 
      
      $('#dynamic-form').on('beforeSubmit', function () {
 
          var form = $(this);
       
          if (form.find('.has-error').length) {
              return false;
          }
          return true; // form gets submitted
          
       
      });
