### ISSUE TITLE
Bug with checkboxes on cloned items

### ISSUE THREAD

**Issue by elastic-od** [wbraganca/yii2-dynamicform#19]
I have found a bug with checkboxes in current version on cloning items.
As you know for each checkbox yii creates hidden input with default {value="0"} and the checkbox itself has default {value="1"}. So we have:

`<input type="hidden" name="Tickets[0][class]" value="0">`
`<input type="checkbox" id="tickets-0-class" class="selectbox" name="Tickets[0][class]" value="1">`

But after cloning all cloned items have both input values as {value}, they lose their default value and after that data aren't sent correctly to controller:

`<input type="hidden" name="Tickets[0][class]" value>`
`<input type="checkbox" id="tickets-0-class" class="selectbox" name="Tickets[0][class]" value>`

I managed to fix it in 'afterClone' event in this way:
```javascript
$('#dynamic-widget').on('afterClone' ,function(e, clonedItem) {
  $(this).find('input:hidden').val(0);
  $(this).find('nput:checkbox').val(1);
});
```

it works for me, but it is not the best solution I guess.
In fact it is not the widget bug but the jquery bug:
http://bugs.jquery.com/ticket/10550
There is described that bug has place in IE but I faced it in Chrome too.

**Comment by wbraganca** [comment]
Bug fixed by the new version
