### ISSUE TITLE
How to know how many item rows has been added by user

### ISSUE THREAD

**Issue by wilsonxyz** [wbraganca/yii2-dynamicform#210]
Hi, in dynamic form i have these fields
```
'formFields' => [
	'id',
	'po_id',
	'item_id',
	'qty',
	'price',
	'total',
	'remark',
],
```
when users add or remove item, i want to sum all the total and save it to one field.
here my javascript
```
function calculateTotal(index){    
    var total = 0;    
    for(i=0; i< index; i++){        
        var subtotal = $('#purchaseorderdetail-' + i + '-total').val();        
        subtotal = subtotal == "" ? 0 : Number(subtotal.split(",").join(""));    
		total = total + subtotal;
    }
    $('#purchaseorder-total').val(total);
}
```
how to define its row count (index)?

**Comment by paulatsfo** [comment]
I got around this problem by doing it in the view after they submit the Create or Update. Then in the view you can use an enhanced Gridview Widget to display totals, counts, averages, etc.

**Comment by wilsonxyz** [comment]
I have solution for this question
`function calculateTotal(){    
    var total = 0;        
    jQuery(".dynamicform_wrapper .remove-item").each(function(index) {
        var subtotal = $('#purchaseorderdetail-' + index + '-total').val();
        if(typeof(subtotal) != 'undefined'){
            subtotal = subtotal == "" ? 0 : Number(subtotal.split(",").join(""));    
            total = total + subtotal;    
        }        
    });
    $('#purchaseorder-total').val(total);
}`
