### ISSUE TITLE
Uncaught TypeError: Cannot read property 'settings' of undefined & $toclone.clone is not a function

### ISSUE THREAD

**Issue by PitBult** [wbraganca/yii2-dynamicform#224]
Hi!
**After updating to Yii2 version 2.0.13.1 I have 2 errors**:
1.
```
yii2-dynamic-form.js:90 Uncaught TypeError: Cannot read property 'settings' of undefined
    at _parseTemplate (yii2-dynamic-form.js:90)
```
2. 
```
Uncaught TypeError: $toclone.clone is not a function
    at _addItem (yii2-dynamic-form.js:119)
```

My source code (default - jQuery JavaScript Library v3.2.1): 
```
<script src="/backend/assets/.../jquery.js"></script>
 <script src="/backend/assets/.../yii.js"></script>
 <script src="/backend/assets/.../yii.validation.js"></script>
 <script src="/backend/assets/.../js/select2.full.js"></script>
 <script src="/backend/assets/.../js/select2-krajee.js"></script>
 <script src="/backend/assets/.../jquery.pjax.js"></script>
 <script src="/backend/assets/.../yii.activeForm.js"></script>
 <script src="/backend/assets/.../yii2-dynamic-form.js"></script>
 <script src="/backend/assets/.../js/plugins/sortable.js"></script>
 <script src="/backend/assets/.../js/plugins/purify.js"></script>
 <script src="/backend/assets/.../js/fileinput.js"></script>
 <script src="/backend/assets/.../js/bootstrap.js"></script>
 <script src="/backend/assets/.../js/extension.js"></script>
```
**Does someone have solutions? Thank you in advance!**

**Comment by alex290** [comment]
Same problem.
Error occurs once

```
yii2-dynamic-form.js:90 Uncaught TypeError: Cannot read property 'settings' of undefined
    at _parseTemplate (yii2-dynamic-form.js:90)
    at HTMLFormElement.<anonymous> (yii2-dynamic-form.js:37)
    at Function.each (jquery.js:362)
    at jQuery.fn.init.each (jquery.js:157)
    at jQuery.fn.init.init (yii2-dynamic-form.js:36)
    at jQuery.fn.init.$.fn.yiiDynamicForm (yii2-dynamic-form.js:19)
    at create:337
    at dispatch (jquery.js:5206)
    at elemData.handle (jquery.js:5014)
```

**Comment by SteveSimpson** [comment]
I am seeing the same error. Looking at the differences between 2.0.12 & 2.0.13.1 in the view source of the html page:
in 2.0.12:    <script type="text/javascript">jQuery(document).ready(function () {
but in 2.0.13.1:  <script type="text/javascript">jQuery(function ($) {

backing down to 2.0.12 solved the 'settings' error (line 90).

I am still seeing the $toclone.clone issue though

**Comment by philippfrenzel** [comment]
same error here - I can't go back to 2.0.12 as this version had big issues with pjax - :/

**Comment by Nik1192** [comment]
same problem
yii2-dynamic-form.js:90 Uncaught TypeError: Cannot read property 'settings' of undefined
    at _parseTemplate (yii2-dynamic-form.js:90)
    at HTMLFormElement.<anonymous> (yii2-dynamic-form.js:37)
    at Function.each (jquery.js:362)
    at jQuery.fn.init.each (jquery.js:157)
    at jQuery.fn.init.init (yii2-dynamic-form.js:36)
    at jQuery.fn.init.$.fn.yiiDynamicForm (yii2-dynamic-form.js:19)
    at index.php?r=po%2Fcreate:862
    at dispatch (jquery.js:5206)
    at elemData.handle (jquery.js:5014)
_parseTemplate @ yii2-dynamic-form.js:90
(anonymous) @ yii2-dynamic-form.js:37
each @ jquery.js:362
each @ jquery.js:157
init @ yii2-dynamic-form.js:36
$.fn.yiiDynamicForm @ yii2-dynamic-form.js:19
(anonymous) @ index.php?r=po%2Fcreate:862
dispatch @ jquery.js:5206
elemData.handle @ jquery.js:5014
index.php?r=po%2Fcreate:102 

 Uncaught TypeError: $toclone.clone is not a function
    at _addItem (yii2-dynamic-form.js:119)
    at jQuery.fn.init.addItem (yii2-dynamic-form.js:42)
    at jQuery.fn.init.$.fn.yiiDynamicForm (yii2-dynamic-form.js:17)
    at HTMLButtonElement.<anonymous> (index.php?r=po%2Fcreate:851)
    at HTMLFormElement.dispatch (jquery.js:5206)
    at HTMLFormElement.elemData.handle (jquery.js:5014)
_addItem @ yii2-dynamic-form.js:119
addItem @ yii2-dynamic-form.js:42
$.fn.yiiDynamicForm @ yii2-dynamic-form.js:17
(anonymous) @ index.php?r=po%2Fcreate:851
dispatch @ jquery.js:5206
elemData.handle @ jquery.js:5014

**Comment by spiro-stathakis** [comment]
Same problem with me too. 
```javascript 
Uncaught TypeError: Cannot read property 'settings' of undefined
    at _parseTemplate (yii2-dynamic-form.js:90)
    at HTMLFormElement.<anonymous> (yii2-dynamic-form.js:37)
    at Function.each (jquery.js:362)
    at jQuery.fn.init.each (jquery.js:157)
    at jQuery.fn.init.init (yii2-dynamic-form.js:36)
    at jQuery.fn.init.$.fn.yiiDynamicForm (yii2-dynamic-form.js:19)
    at update:2508
    at dispatch (jquery.js:5206)
    at elemData.handle (jquery.js:5014)
2yii2-dynamic-form.js:119 Uncaught TypeError: $toclone.clone is not a function
    at _addItem (yii2-dynamic-form.js:119)
    at jQuery.fn.init.addItem (yii2-dynamic-form.js:42)
    at jQuery.fn.init.$.fn.yiiDynamicForm (yii2-dynamic-form.js:17)
    at HTMLButtonElement.<anonymous> (update:2486)
    at HTMLFormElement.dispatch (jquery.js:5206)
    at HTMLFormElement.elemData.handle (jquery.js:5014)
```

**Comment by mastershaig** [comment]
@SteveSimpson thanks for clone ! It worked like a charm !
Did you send pull request to fix this bug?

**Comment by SteveSimpson** [comment]
yep - I took the time to create a branch with just the changes to be applied & nothing, would be nice to have someone maintain this code

**Comment by akula22** [comment]
What needs to be changed in the code to solve this problem?

**Comment by PitBult** [comment]
> What needs to be changed in the code to solve this problem?

("composer.json") Change line to : 
`"wbraganca/yii2-dynamicform": "*"`

run command >> `composer update`

**Comment by akula22** [comment]
did not help

Uncaught TypeError: $toclone.clone is not a function
    at _addItem (yii2-dynamic-form.js:119)
    at jQuery.fn.init.addItem (yii2-dynamic-form.js:42)
    at jQuery.fn.init.$.fn.yiiDynamicForm (yii2-dynamic-form.js:17)
    at HTMLButtonElement.<anonymous> (create:786)
    at HTMLFormElement.dispatch (jquery.js:5206)
    at HTMLFormElement.elemData.handle (jquery.js:5014)

**Comment by sniper888** [comment]
DynamicFormWidget.php :219

`$js = 'jQuery("#' . $this->formId . '").on(\'afterInit\', function () {jQuery("#' . $this->formId . '").yiiDynamicForm(' . $this->_hashVar .');});' . "\n";
        $view->registerJs($js, $view::POS_LOAD);`

**Comment by shashi53** [comment]
comment below link in js 
 var yiiActiveFormData = $('#' + widgetOptions.formId).yiiActiveForm('data');
  // $template.find('.' + yiiActiveFormData.settings.errorCssClass).removeClass(yiiActiveFormData.settings.errorCssClass);
    // $template.find('.' + yiiActiveFormData.settings.successCssClass).removeClass(yiiActiveFormData.settings.successCssClass);

then code will work

**Comment by maxneh** [comment]
@sniper888 that help only IE, Edge, Safari, but after add - not work in Chrome and other(

**Comment by IgorCode** [comment]
Changing `$toclone = widgetOptions.template;` to `$toclone = $(widgetOptions.template);` seems to resolve the issue with `TypeError: $toclone.clone is not a function` error.

**Comment by rklvnoe** [comment]
> Changing `$toclone = widgetOptions.template;` to `$toclone = $(widgetOptions.template);` seems to resolve the issue with `TypeError: $toclone.clone is not a function` error.

Worked for me to.

**Comment by Legion112** [comment]
@rklvnoe  
@IgorCode 
Thank you all.

**Comment by den11100** [comment]
> Changing `$toclone = widgetOptions.template;` to `$toclone = $(widgetOptions.template);` seems to resolve the issue with `TypeError: $toclone.clone is not a function` error.

It work for me to. Work in firefox and chrome

but is not good changing vendor/wbraganca/yii2-dynamicform/src/assets/yii2-dynamic-form.js

**Comment by nikhil1729** [comment]
its not working when page is opened, but working after refreshing page. Can any help me?

**Comment by curtis18** [comment]
@shashi53 
Thank you. Comment these lines and bundle an updated yii2-dynamic-form.js can solve the problem.
https://github.com/wbraganca/yii2-dynamicform/issues/104#issuecomment-330001127
> 
> 
> @@@#comment below line in js
> 
> it is under _parseTemplate varible
> // var yiiActiveFormData = $('#' + widgetOptions.formId).yiiActiveForm('data');
> // $template.find('.' + yiiActiveFormData.settings.errorCssClass).removeClass(yiiActiveFormData.settings.errorCssClass);
> // $template.find('.' + yiiActiveFormData.settings.successCssClass).removeClass(yiiActiveFormData.settings.successCssClass);
> 
> then code will work

**Comment by jose05chandia** [comment]
If dont you solve this situation modifying  

```
$js = 'jQuery("#' . $this->formId . '").on(\'afterInit\', function () {jQuery("#' . $this->formId . '").yiiDynamicForm(' . $this->_hashVar .');});' . "\n"; $view->registerJs($js, $view::POS_LOAD);

in DynamicFormWidget.php
and 

$toclone = widgetOptions.template; to $toclone = $(widgetOptions.template);

in yii2-dynamic-form.js 
```

**in my situation, i had linked twice the file "jquery.js". 
I solved using** http://code.jquery.com/jquery-2.1.0.min.js and deleting the duplicated link.

**Comment by xero-q** [comment]
> 
> 
> Changing `$toclone = widgetOptions.template;` to `$toclone = $(widgetOptions.template);` seems to resolve the issue with `TypeError: $toclone.clone is not a function` error.

Thanks, it worked for me too.

**Comment by ftnxhzqh** [comment]
> Changing `$toclone = widgetOptions.template;` to `$toclone = $(widgetOptions.template);` seems to resolve the issue with `TypeError: $toclone.clone is not a function` error.

thank you. it worked for me too.
