### ISSUE TITLE
The models desappear when "enableClientValidation" to false

### ISSUE THREAD

**Issue by timmy78** [wbraganca/yii2-dynamicform#23]
In the ActiveForm config, if I put ```enableClientValidation```  to false, and then there are errors in the models, the models don't appear in the form.

I have the same problem in the create scenario : if before I declare some models with attributes, they don't appear in the form.

How to make it work like in the update scenario ?

-----

More informations : it's the javascript of the widget which delete the items. If I don't use the widget it appears.

-----

Thank you

**Comment by wbraganca** [comment]
Which version of yii2 are you using?

**Comment by timmy78** [comment]
The last one I suppose : ```"yiisoft/yii2": "*",```

**Comment by wbraganca** [comment]
I did not find any problem. Put here the code of your view.

![dynamicform-issue-23](https://cloud.githubusercontent.com/assets/1946359/6529098/3c44ef94-c405-11e4-9d9c-6412014b3272.jpg)

**Comment by timmy78** [comment]
Did you tried in the actionCreate : 
```
$modelsAddress = [
  new Address([
    'full_name' => 'test'
  ]),
  new Address([
    'full_name' => 'test2'
  ]),
];
```

**Comment by timmy78** [comment]
I figured out !
That was because I put ```'min' => 0``` instead of ```1```
