### ISSUE TITLE
Cant save to DB

### ISSUE THREAD

**Issue by wennaspeedy** [wbraganca/yii2-dynamicform#29]
Hi, Iam trying this extension. Everything works, but if I want to create new one and save to database, nothing happens. If I add record to DB in sql, I can see it in yii with your extension, but cant update... whats wrong? I mean your example. thanx.

**Comment by wbraganca** [comment]
How is the code in your view?

**Comment by wennaspeedy** [comment]
it's the same as in your example. everything is same. I only created database (according to image) and generated models and CRUD.

**Comment by wbraganca** [comment]
Add the following code in your view. And see what error appears.

```php
<?php
    var_dump($modelCustomer->getErrors());
    foreach ($modelsAddress as $modelAddress) {
        var_dump($modelAddress->getErrors());
    }
?>
```
 This seems to be error field validation "customer_id" in the model address. If so, set the rule to "customer_id" only required when updating.

**Comment by wennaspeedy** [comment]
When I want to create new one, I get error: 

array (size=0)
  empty

array (size=1)
  'customer_id' => 
    array (size=1)
      0 => string 'Customer ID cannot be blank.' (length=28)

**Comment by wbraganca** [comment]
Change the validation rules in your model "Address":

```php
public function rules()
{
    return [
        [['customer_id', 'full_name', 'address_line1', 'city', 'state', 'postal_code'], 'required'],// change here
        ....
    ];
}
```

To

```php


public function rules()
{
    return [
        [['full_name', 'address_line1', 'city', 'state', 'postal_code'], 'required'],
        [['customer_id'], 'required', 'on' => 'update'],
        ....
    ];
}

```

**Comment by wennaspeedy** [comment]
It seems to be ok. thank you very much! :)
