### ISSUE TITLE
Issue with kartik-v Select2 widget

### ISSUE THREAD

**Issue by kozerog91** [wbraganca/yii2-dynamicform#43]
After adding one more item to dynamic form - the Select2 widget appears with style="display:none". 
Also returns error in console: The select2('destroy') method was called on an element that is not using Select2.
![image](https://cloud.githubusercontent.com/assets/9293253/7787152/5891a082-0205-11e5-8ad6-b163cce0d59c.png)

**Comment by aivarasb** [comment]
Multiple select2 widgets which refers to same model field are hidden for some reason with no errors. Removing display: none it works perfectly.

**Comment by Lordfef** [comment]
Hi aivarasb, i have the same issue, how can i remove style="display: none" from select? Must i work on my css or is there a param in the select2? thank's

**Comment by aivarasb** [comment]
Hey Lordfef, seems this wasn't a way to solve this issue completely. To solve it what I have done is created different field where would you store select option. For example:
```
<?php
echo $form->field($modeld, 'temp_id3')->widget(\kartik\widgets\Select2::classname(), [
 'data' => $data,
])->label('Article');
?>
<?php
echo $form->field($modeld, 'temp_id2')->widget(\kartik\widgets\Select2::classname(), [
 'data' => $data,
])->label('Article');
?>
```
and then in the backend do all custom stuff.
