### ISSUE TITLE
DEMO 3

### ISSUE THREAD

**Issue by kaarleenzz** [wbraganca/yii2-dynamicform#45]
Hi @wbraganca , could you give us the code used in 'DEMO 3' ?
http://wbraganca.com/yii2extensions/dynamicform-demo3/

I know there are a lot of people waiting for it...

**Comment by cloudcaptain** [comment]
yes, please post

**Comment by adiramardiani** [comment]
I think for example in **demo 2** too...

**Comment by cloudcaptain** [comment]
Suggest closing this issue - reference Wiki:
https://github.com/wbraganca/yii2-dynamicform/wiki/Nested-Forms-Example
