### ISSUE TITLE
feature requested: click header to collapse

### ISSUE THREAD

**Issue by duynguyen0511** [wbraganca/yii2-dynamicform#48]
Hi @wbraganca 

it's nice to be able to click the header to collapse dynamic form 

![click-to-collapse](https://cloud.githubusercontent.com/assets/436950/8040021/a619d934-0dca-11e5-8742-8f03b698f752.png)

click on top-level header should collapse everything , however, click on second-level header should collapse lower levels

**Comment by Faryshta** [comment]
http://www.yiiframework.com/doc-2.0/yii-bootstrap-collapse.html

you can use this with `label` being the form header and `content`being the form items

**Comment by wbraganca** [comment]
@Faryshta Thank you very much.

**Comment by cyanoboy** [comment]
@Faryshta can you show a practical example? My form is very big and putting it inside label and content parameters of the Yii2 Collapse plugin is not working for me.

**Comment by Faryshta** [comment]
@cyanoboy can you show me an example of your form?
