### ISSUE TITLE
Ist not working with Select2 or Typeahead widgets

### ISSUE THREAD

**Issue by skeeran** [wbraganca/yii2-dynamicform#5]
Hi, i was looking for somthing like this...

but this only works with basic html input fields... not with yii2 known 
select2(https://github.com/kartik-v/yii2-widget-select2) 
or Typeahead(https://github.com/kartik-v/yii2-widget-typeahead) etc..

Fot the first row it is working.. secound row is not loading properly... you have any solution or tips to get this to work

**Comment by charithAmila** [comment]
i update latest version but still not working

**Comment by vaibhavk01** [comment]
hi,
is this extension now working for typehead?

**Comment by dariopalmisano** [comment]
Hello,

thanks for you nice yii2-dynamicform.

Unfortunately even for me typeahead is not working.

Do you have any plan about it/

Thanks in advance

**Comment by vilkh3m** [comment]
@dariopalmisano check this file:
https://github.com/vilkh3m/yii2-dynamicform/blob/master/src/assets/yii2-dynamic-form.js
and compare with your code lines from 457 to 465 this fix my problem 

but im unable to use this via composer :( i just copy code from github

**Comment by dariopalmisano** [comment]
Thanks  vilkh3m for your quick response.

Unfortunately I already applied that patch to make yii2-widget-select2 work in a yii2-dynamicform field!

Regards

**Comment by imdad6053** [comment]
Dear your problem solved or not?
I faced same problem.
Did you find typehead dynamic form solution?

**Comment by vilkh3m** [comment]
> Dear your problem solved or not?
> I faced same problem.
> Did you find typehead dynamic form solution?

did you try this: https://github.com/wbraganca/yii2-dynamicform/pull/292/commits/aeff3d0d18fb1c515f64db6d5e6052074264937e ?
