### ISSUE TITLE
TypeError: WidgetsOptions[i] is undefined

### ISSUE THREAD

**Issue by ald3rson** [wbraganca/yii2-dynamicform#69]
![capture3](https://cloud.githubusercontent.com/assets/13324608/8898083/7bb6f2f0-3451-11e5-8ce3-b9411953e835.JPG)

**Comment by ald3rson** [comment]
this is my code when passing data (jquery)

![capture4](https://cloud.githubusercontent.com/assets/13324608/8898138/2d90aae8-3452-11e5-84b2-4e1ae9103bd2.JPG)

**Comment by ald3rson** [comment]
The second form must have the value 15.40.. I cant figured out whats the problem with this. I know my js code is fine....

**Comment by svok** [comment]
Hi,
replace "identifiers[i] = $elem.closest(widgetsOptions[i].widgetItem).index();" in yii2-dynamic-form.js at 199 by "identifiers[i] = $elem.closest(widgetsOptions[i**-1**].widgetItem).index();"

**Comment by ald3rson** [comment]
thanks, i already solve this problem.

**Comment by crafthmis** [comment]
Oh Thanks. This solved the problem. Thanks Man!!!

**Comment by leonardojulius** [comment]
my problem is how to triger to aufo fil at second elements doesnt work

**Comment by pptyasar** [comment]
Still getting error my version fa1fec0

**Comment by AliBayat** [comment]
i am using this component in my laravel project. and it had a weird bug..

i had planted modals with map in them
and everything seemed to work well
but when i chose locations and try to add new Dynamic sections, i would get the same error

for me
widgetsOptions[i-1].widgetItem
fixed the problem.

though it might help someone else

**Comment by maniwhereitz** [comment]
> identifiers[i] = $elem.closest(widgetsOptions

This worked for me. Thanks
