### ISSUE TITLE
Kartik Select2 problem

### ISSUE THREAD

**Issue by robertolucas** [wbraganca/yii2-dynamicform#76]
Fist of all, thaks a lot for the widget, it is fantastic.

I have a problem with select2 widget.

First time the widget works fine but there is a loading symbol in the form.

The next time you add a new item only the loading symbol is shown.

Could you help me please?

Thanks a lot.

This is the code:

 

    <?= $form->field($modelAlumno, 'idalum')->textInput() ?>

    <?= $form->field($modelAlumno, 'nombre')->textInput(['maxlength' => true]) ?>

    <?= $form->field($modelAlumno, 'apellidos')->textInput(['maxlength' => true]) ?>

    <?= $form->field($modelAlumno, 'mail')->textInput(['maxlength' => true]) ?>

    <?php DynamicFormWidget::begin([
        'widgetContainer' => 'dynamicform_wrapper', // required: only alphanumeric characters plus "_" [A-Za-z0-9_]
        'widgetBody' => '.container-items', // required: css class selector
        'widgetItem' => '.item', // required: css class
        'limit' => 10, // the maximum times, an element can be added (default 999)
        'min' => 0, // 0 or 1 (default 1)
        'insertButton' => '.add-item', // css class
        'deleteButton' => '.remove-item', // css class
        'model' => $modelsOptativa[0],
        'formId' => 'dynamic-form',
        'formFields' => [
            'idsesion',
        ],
    ]); ?>
    
     <div class="panel panel-default">
        <div class="panel-heading">
            <h4>
                <i class="glyphicon glyphicon-envelope"></i> Optativas
                <button type="button" class="add-item btn btn-success btn-sm pull-right"><i class="glyphicon glyphicon-plus"></i> Add</button>
            </h4>
        </div>
        <div  class="panel-body">
            <div class="container-items">
            <?php foreach ($modelsOptativa as $i => $modelOptativa): ?>
                <div class="item panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title pull-left">Optativa</h3>
                        <div class="pull-right">
                            <button type="button" class="remove-item btn btn-danger btn-xs"><i class="glyphicon glyphicon-minus"></i></button>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div id="formulario" class="panel-body">
                      
                      
                                <?= $form->field($modelOptativa, "[{$i}]idsesion")->widget(Select2::classname(), [
                                            'language' => 'en',
                                            'options' => ['placeholder' => 'Search For Contact ...'],
                                            'pluginOptions' => [
                                                'allowClear' => true,
                                                'minimumInputLength' => 3,
                                                'ajax' => [
                                                    'url' => $url,
                                                    'dataType' => 'json',
                                                    'data' => new JsExpression('function(params) { return {q:params.term}; }')
                                                ],
                                            ]
                                        ]); ?>        
                
                
                        
                 
                    </div>
                </div>
            <?php endforeach; ?>
            </div>
        </div>
    </div>
    
    <?php DynamicFormWidget::end(); ?>

![dinamicform](https://cloud.githubusercontent.com/assets/11507801/9249324/0448ba8e-41c4-11e5-8600-cf3b605faf44.jpg)

**Comment by bbod** [comment]
Looks like a similar problem to mine: https://github.com/wbraganca/yii2-dynamicform/issues/75

May be the issue is specific to the Select2 widget and/or when using ajax?

Mine works fine when you switch back to standard text boxes.

Do you get any messages in your console?

**Comment by robertolucas** [comment]
I have no messages in the console.

I've loaded the data vía array and it hasn't worked.

It works with standard dropboxlist.

I've updated select2 and dynamicform, it doesnt solve the problem.

It could be the same problem i had with select2 in and search in gridview...

Could you help me? If i find the solution i'll post it.

**Comment by bbod** [comment]
Think I have found the fix!

Looks like someone else had the problem, see here:

https://github.com/wbraganca/yii2-dynamicform/pull/58/files

I had to go into the repository (forked) on his page:

https://github.com/TimNZ/yii2-dynamicform/blob/master/src/assets/yii2-dynamic-form.js

Copy and replace the code from line 439 to 476 (inclusive) into your yii2-dynamic-form.js

Make sure you copy it into the assets folder not the vendor folder.

So my file /assets/32c72876/yii2-dynamic-form.js now looks like this:

         // "kartik-v/yii2-widget-select2"
        var $hasSelect2 = $(widgetOptionsRoot.widgetItem).find('[data-krajee-select2]');
        if ($hasSelect2.length > 0) {
            $hasSelect2.each(function() {
                var id = $(this).attr('id');
                var configSelect2 = eval($(this).attr('data-krajee-select2'));

                if ($(this).data('select2')) {
                    $(this).select2('destroy');
                }

                var configDepdrop = $(this).data('depdrop');
                if (configDepdrop) {
                    configDepdrop = $.extend(true, {}, configDepdrop);
                    $(this).removeData().off();
                    $(this).unbind();
                    _restoreKrajeeDepdrop($(this));
                }
                var s2LoadingFunc = typeof initSelect2Loading != 'undefined' ? initSelect2Loading : initS2Loading;
                var s2OpenFunc = typeof initSelect2DropStyle != 'undefined' ? initSelect2Loading : initS2Loading;
                $.when($('#' + id).select2(configSelect2)).done(s2LoadingFunc(id, '.select2-container--krajee'));

                var kvClose = 'kv_close_' + id.replace(/\-/g, '_');

                $('#' + id).on('select2:opening', function(ev) {
                    s2OpenFunc(id, kvClose, ev);
                });

                $('#' + id).on('select2:unselect', function() {
                    window[kvClose] = true;
                });

               if (configDepdrop) {
                    var loadingText = (configDepdrop.loadingText) ? configDepdrop.loadingText : 'Loading ...';
                    initDepdropS2(id, loadingText);
                }
            });
        }		
		
		/*
        // "kartik-v/yii2-widget-select2"
        var $hasSelect2 = $(widgetOptionsRoot.widgetItem).find('[data-krajee-select2]');
        if ($hasSelect2.length > 0) {
            $hasSelect2.each(function() {
                var id = $(this).attr('id');
                var configSelect2 = eval($(this).attr('data-krajee-select2'));
                $(this).select2('destroy');
                $.when($('#' + id).select2(configSelect2)).done(initS2Loading(id));
                
				$('#' + id).on('select2-open', function() {
                    initS2Open(id)
                });
				
                if ($(this).attr('data-krajee-depdrop')) {
                    $(this).on('depdrop.beforeChange', function(e,i,v) {
                        var configDepdrop = eval($(this).attr('data-krajee-depdrop'));
                        var loadingText = (configDepdrop.loadingText)? configDepdrop.loadingText : 'Loading ...';
                        $('#' + id).select2('data', {text: loadingText});
                    });
                    $(this).on('depdrop.change', function(e,i,v,c) {
                        $('#' + id).select2('val', $('#' + id).val());
                    });
                }
            });
        }
		*/

Now I get:

![image](https://cloud.githubusercontent.com/assets/12124507/9272595/183c65dc-427c-11e5-851b-49c1c3d98fa0.png)


Hope that helps!

**Comment by robertolucas** [comment]
Thank you very much indeed!!

You've solved my problem.

See you.

**Comment by leonardojulius** [comment]
add button doesnt work

**Comment by leonardojulius** [comment]
Hmm Thnx It worked!

**Comment by lgyaguapaz** [comment]
Thank you very much. It works perfectly

**Comment by webthurwa** [comment]
Where do you make this change? 
I do not have this in my assets folder. I only have AppAsset.php there and yii2-dynamic-form.js is in the vendor folder (to be precise assets in vendor folder).

**Comment by tanmay20** [comment]
I don't understand why it's not working for me  -

```
// "kartik-v/yii2-widget-depdrop"
        var $hasDepdrop = $(widgetOptionsRoot.widgetItem).find('[data-krajee-depdrop]');
        if ($hasDepdrop.length > 0) {
            $hasDepdrop.each(function() {
                if ($(this).data('select2') === undefined) {
                    $(this).removeData().off();
                    $(this).unbind();
                    _restoreKrajeeDepdrop($(this));
                }
                
            });
        }

        // "kartik-v/yii2-widget-select2"
        var $hasSelect2 = $(widgetOptionsRoot.widgetItem).find('[data-krajee-select2]');
        if ($hasSelect2.length > 0) {
            $hasSelect2.each(function() {
                var id = $(this).attr('id');
                var configSelect2 = eval($(this).attr('data-krajee-select2'));

                    if ($(this).data('select2')) {
                    $(this).select2('destroy');
                }

                var configDepdrop = $(this).data('depdrop');
                if (configDepdrop) {
                    configDepdrop = $.extend(true, {}, configDepdrop);
                    $(this).removeData().off();
                    $(this).unbind();
                    _restoreKrajeeDepdrop($(this));
                }

                var s2LoadingFunc = typeof initSelect2Loading != 'undefined' ? initSelect2Loading : initS2Loading;
                var s2OpenFunc = typeof initSelect2DropStyle != 'undefined' ? initSelect2Loading : initS2Loading;
                $.when($('#' + id).select2(configSelect2)).done(initS2Loading(id, '.select2-container--krajee'));

                    var kvClose = 'kv_close_' + id.replace(/\-/g, '_');

                    $('#' + id).on('select2:opening', function(ev) {
                        s2OpenFunc(id, kvClose, ev);
                });
                $('#' + id).on('select2:unselect', function() {
                    window[kvClose] = true;
                });

                if (configDepdrop) {
                    var loadingText = (configDepdrop.loadingText) ? configDepdrop.loadingText : 'Loading ...';
                    initDepdropS2(id, loadingText);
                }
            });
        }
```
I still get the spinning symbol on top of the select2 field. Details here - http://stackoverflow.com/questions/38940017/select2-and-wbraganca-yii2-dynamicform-not-working-together-in-yii2
![error_5](https://cloud.githubusercontent.com/assets/9931557/17649552/f4688fb4-6255-11e6-9437-dc9ebc08c838.JPG)

**Comment by tanmay20** [comment]
I've found a solution to remove the spinning icon on the select2. I've removed the 'id' from select2 widget in my _form and that resolved this issue.

**Comment by ahmadfadlydziljalal** [comment]
@tanmay20, where the spinning icon and how to remove that id ?

**Comment by felipe-carrasco** [comment]
@ahmadfadlydziljalal, look at the comment made @bbod  , you need to copy from line 439 to 476 (inclusive) from the fork he posted and replace in your web/assets/<some-hash-number>/yii2-dynamic-form.js file (you will have to look inside all the folders that are in assets until you find the file).
You have to replace from around line 410 in you yii2-dynamic-form.js

**Comment by abusalwa** [comment]
@tanmay20 how to remove 'id' from _form ?

**Comment by eothein** [comment]
But adding this in the assets folder does not realy solve the problem, as a new load would just load the old javascript file, or am I misunderstanding something here?

**Comment by tonyleone** [comment]
Has this issue been addressed with the latest version?  I am using a somewhat older version and I would update if it is fixed?

**Comment by firmanyuspriyadi** [comment]
@bbod  you save my live .. thanx

**Comment by sr1234** [comment]
This was a lifesaver for sure.  Thanks @bbod for posting this solution.  So I got it working perfectly when the nested form only has one field using the Kartik Select2 widget.  But once I added a second field, I ran into the same problem.

So to clarify, my nested model only has two fields:
Field #1: service_id (I am using Kartik's Select2 widget for this)
Field #2: amount (this is a plain number field, not even using the Select2 widget!)

When I added Field #2, I got the same spinner that was popping up in the Select2 field, when clicking the [+] icon to add another service.   

So it seems like this solution only works when you have 1 field!  So I am back to the drawing board.

@bbod, did you manage to ever get this working with more than just one field?  The second field can be of any type, and doesn't have to use the Select2 widget.    If so, any hints on how to resolve this would be greatly appreciated.  Thanks

**Comment by ElianaFarinango8** [comment]
@bbod thanks

**Comment by yuriystank** [comment]
In `composer.json` changing `wbraganca/yii2-dynamicform` to "dev-master" worked for me. `kartik-v/yii2-widget-select2` version is "2.0.0"

**Comment by francis22** [comment]
While updating form first value used in select2 will be the default value of the newly added select2 filed. how we can set it as empty

**Comment by MUHAMMADTAYYAB** [comment]
Thanks it works
