### ISSUE TITLE
Validating additional fields

### ISSUE THREAD

**Issue by loter** [wbraganca/yii2-dynamicform#9]
Hello,

Very good extension!
I've implemented dynamicform in my project, but looks like it doesn't validate the additional fields created (for example if I click on [+] then try to submit form, only the initial form validates.)

Please advice! Thank you!

**Comment by demigorian** [comment]
I have problem with update in dynamic forms. Please help me...I'm beginner in php
This is my actionupdate

public function actionUpdate($id) {
        
        $model = $this->findModel($id);
        $modelsCtel = $model->ctels;
        $modelsDvr = $model->dvrs;
        
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            
            $oldIDs = ArrayHelper::map($modelsCtel, 'id', 'id');
            $oldIDs = ArrayHelper::map($modelsDvr, 'id', 'id');
            
            $modelsCtel = Model::createMultiple(Ctel::classname(), $modelsCtel);
            Model::loadMultiple($modelsCtel, Yii::$app->request->post());
            
            $modelsDvr = Model::createMultiple(Dvr::classname(), $modelsDvr);
            Model::loadMultiple($modelsDvr, Yii::$app->request->post());
            
            $deletedIDs = array_diff($oldIDs, array_filter(ArrayHelper::map($modelsCtel, 'id', 'id')));
            $deletedIDs = array_diff($oldIDs, array_filter(ArrayHelper::map($modelsDvr, 'id', 'id')));
            // ajax validation
             
            
            // validate all models
            $valid = $model->validate();
            $valid = Model::validateMultiple($modelsCtel) && $valid;
            $valid = Model::validateMultiple($modelsDvr) && $valid;
            if ($valid) {
                $transaction = \Yii::$app->db->beginTransaction();
                try {
                    if ($flag = $model->save(false)) {
                        
                        if (! empty($deletedIDs)) {
                            Ctel::deleteAll(['id' => $deletedIDs]);
                        }
                        
                        if (! empty($deletedIDs)) {
                            Dvr::deleteAll(['id' => $deletedIDs]);
                        }
                        
                        foreach ($modelsCtel as $modelCtel) {
                            $modelCtel->id_client = $model->id;
                            if (!($flag = $modelCtel->save(false))) {
                                $transaction->rollBack();
                                break;
                            }
                        }
                        
                        foreach ($modelsDvr as $modelDvr) {
                            $modelDvr->id_client = $model->id;
                            if (!($flag = $modelDvr->save(false))) {
                                $transaction->rollBack();
                                break;
                            }
                        }
                    }
                    if ($flag) {
                        $transaction->commit();
                        return $this->redirect(['view', 'id' => $model->id]);
                    }
                } catch (Exception $e) {
                    $transaction->rollBack();
                }
            }
        } else {
            return $this->render('update', [
                        'model' => $model,
                        'modelsCtel' => (empty($modelsCtel)) ? [new Ctel] : $modelsCtel,
                        'modelsDvr' =>(empty($modelsDvr)) ? [new Dvr] : $modelsDvr
            ]);
        }

**Comment by fullflash** [comment]
customer_id is required field and will fail on line Model.validateMultiple
